Repository ChainSafe/filecoindot, pull requests merged in 2021-11, with the labels that each got.

#60 feat(ocw): add rpc call for setting filecoin rpc endpoint
  Cargo.lock
  Cargo.toml
  filecoindot-ocw/Cargo.toml
  filecoindot-ocw/src/crypto.rs
  filecoindot-ocw/src/lib.rs
  filecoindot-ocw/src/ocw.rs
  filecoindot-ocw/src/result.rs
  filecoindot-ocw/src/tests/mock.rs
  filecoindot-ocw/src/tests/mod.rs
  filecoindot-rpc/Cargo.toml
  filecoindot-rpc/src/lib.rs
  filecoindot-rpc/src/result.rs
  substrate-node-example/node/Cargo.toml
  substrate-node-example/node/src/rpc.rs
  substrate-node-example/node/src/service.rs
  substrate-node-example/runtime/src/lib.rs
Labels: Status: Approved

#66 feat(ocw): vote blocks in ocw
  Cargo.lock
  filecoindot-ocw/Cargo.toml
  filecoindot-ocw/src/api/chain_head.rs
  filecoindot-ocw/src/api/get_tip_set_by_height.rs
  filecoindot-ocw/src/api/mod.rs
  filecoindot-ocw/src/de.rs
  filecoindot-ocw/src/lib.rs
  filecoindot-ocw/src/ocw.rs
  filecoindot-ocw/src/result.rs
  filecoindot-ocw/src/tests/data.rs
  filecoindot-ocw/src/tests/mod.rs
  filecoindot-ocw/src/tests/types.rs
  filecoindot-ocw/src/types.rs
Labels: Status: Approved

#67 chore(ocw): move filecoindot-ocw to filecoiindot/ocw
  Cargo.lock
  Cargo.toml
  filecoindot-ocw/Cargo.toml
  filecoindot-ocw/src/lib.rs
  filecoindot/Cargo.toml
  filecoindot/src/crypto.rs
  filecoindot/src/lib.rs
  filecoindot/src/ocw/api/chain_head.rs
  filecoindot/src/ocw/api/chain_height.rs
  filecoindot/src/ocw/api/get_tip_set_by_height.rs
  filecoindot/src/ocw/api/mod.rs
  filecoindot/src/ocw/de.rs
  filecoindot/src/ocw/mod.rs
  filecoindot/src/ocw/result.rs
  filecoindot/src/ocw/tests/data.rs
  filecoindot/src/ocw/tests/ext/db.rs
  filecoindot/src/ocw/tests/ext/env.rs
  filecoindot/src/ocw/tests/ext/ext.rs
  filecoindot/src/ocw/tests/ext/mod.rs
  filecoindot/src/ocw/tests/ext/result.rs
  filecoindot/src/ocw/tests/ext/state.rs
  filecoindot/src/ocw/tests/get_tip_set_by_height.rs
  filecoindot/src/ocw/tests/mod.rs
  filecoindot/src/ocw/tests/pallet.rs
  filecoindot/src/ocw/types.rs
  filecoindot/src/tests/mock.rs
  substrate-node-example/runtime/Cargo.toml
  substrate-node-example/runtime/src/lib.rs
Labels: Status: Approved

#68 feat(ocw): add timeout logic to the offchain worker
  filecoindot/src/lib.rs
  filecoindot/src/ocw/api/mod.rs
  filecoindot/src/ocw/mod.rs
  filecoindot/src/ocw/tests/mod.rs
  filecoindot/src/tests/mock.rs
  substrate-node-example/runtime/src/lib.rs
Labels: Status: Approved

#70 Add document for setting filecoindot
  Cargo.lock
  README.md
  substrate-node-example/README.md
Labels: Status: Changes Requested

#76 feat(ocw): add tests for submitting signed transactions
  Cargo.lock
  filecoindot/Cargo.toml
  filecoindot/src/ocw/api/get_tip_set_by_height.rs
  filecoindot/src/ocw/api/mod.rs
  filecoindot/src/ocw/mod.rs
  filecoindot/src/ocw/tests/ext/env.rs
  filecoindot/src/ocw/tests/ext/mod.rs
  filecoindot/src/ocw/tests/mod.rs
  filecoindot/src/ocw/tests/pallet.rs
  filecoindot/src/tests/mock.rs
  filecoindot/src/tests/mod.rs
  filecoindot/src/tests/ocw.rs
Labels: Status: Approved

#56 ci(benchmark): run benchmarks after testing
  .github/workflows/tests.yml
  Cargo.lock
  filecoindot_proofs/src/amt.rs
Labels: Status: Review Needed

#92 feat(types): add javascript types
  .gitignore
  Cargo.lock
  js/e2e/.eslintrc.js
  js/e2e/README.md
  js/e2e/index.ts
  js/e2e/package.json
  js/e2e/src/api.ts
  js/e2e/src/index.ts
  js/e2e/tsconfig.json
  js/package.json
  js/types/index.ts
  js/types/package.json
  js/yarn.lock
  resources/types.json
Labels: Status: Review Needed

#80 feat(docker): build and push filecoindot-template docker image
  .github/workflows/docker.yml
  Cargo.lock
  Dockerfile
  substrate-node-example/node/Cargo.toml
Labels: Status: Review Needed

#97 feat(js): add e2e testing
  .github/workflows/tests.yml
  Cargo.lock
  filecoindot/src/ocw/api/chain_height.rs
  filecoindot/src/ocw/api/mod.rs
  filecoindot/src/ocw/mod.rs
  filecoindot/src/ocw/tests/mod.rs
  js/e2e/.gitignore
  js/e2e/index.ts
  js/e2e/package.json
  js/e2e/src/api.ts
  js/e2e/src/launch.ts
  js/e2e/src/runner.ts
  js/package.json
  js/yarn.lock
Labels: Status: Approved

#101 docs(relayer): add docs for adding relayer
  README.md
Labels: Status: Changes Requested

#89 added receipt and state verification
  Cargo.lock
  Cargo.toml
  filecoindot-io/Cargo.toml
  filecoindot-io/README.md
  filecoindot-io/src/lib.rs
  filecoindot-proofs/Cargo.toml
  filecoindot-proofs/src/amt.rs
  filecoindot-proofs/src/errors.rs
  filecoindot-proofs/src/forest_amt_adaptor.rs
  filecoindot-proofs/src/forest_hamt_adaptor.rs
  filecoindot-proofs/src/generate.rs
  filecoindot-proofs/src/hamt.rs
  filecoindot-proofs/src/lib.rs
  filecoindot-proofs/src/traits.rs
  filecoindot-proofs/src/verify.rs
  filecoindot-rpc/Cargo.toml
  filecoindot/Cargo.toml
  filecoindot/src/lib.rs
  filecoindot/src/tests/benchmarking.rs
  filecoindot/src/tests/mock.rs
  filecoindot/src/tests/mod.rs
  filecoindot/src/tests/verify.rs
  filecoindot/src/types.rs
  substrate-node-example/README.md
  substrate-node-example/node/Cargo.toml
  substrate-node-example/node/src/service.rs
Labels: Status: Approved

#106 chore(docker): fix docker push again...
  .github/workflows/docker.yml
Labels: Status: Review Needed

#102 feat(rpc): add verifying RPC apis
  Cargo.lock
  filecoindot-rpc/Cargo.toml
  filecoindot-rpc/src/lib.rs
Labels: Status: Review Needed
