Repository ChainSafe/filecoindot, pull requests merged in 2022-01, with the labels that each got.

#139 doc(cli): install with nightly toolchain
  cli/README.md
Labels: Status: Review Needed

#132 feat(setup): add setup script
  .github/workflows/tests.yml
  README.md
  js/e2e/setup.ts
  js/e2e/src/runner.ts
  js/package.json
  js/yarn.lock
  scripts/setup.json
  scripts/setup.sh
Labels: Status: Approved, Status: Review Needed

#117 feat(rpc): supports multiple rpc endpoints
  Cargo.lock
  README.md
  filecoindot-rpc/Cargo.toml
  filecoindot-rpc/src/lib.rs
  filecoindot/src/ocw/api/mod.rs
  filecoindot/src/ocw/mod.rs
  filecoindot/src/ocw/result.rs
  filecoindot/src/tests/ocw.rs
  js/e2e/index.ts
  js/e2e/package.json
  js/e2e/src/api.ts
  js/e2e/src/runner.ts
  js/types/index.ts
  js/yarn.lock
Labels: Status: Approved

#134 publish javascript types in CI
  .github/workflows/publish.yml
  .github/workflows/tests.yml
  .gitignore
  js/e2e/package.json
  js/e2e/src/api.ts
  js/e2e/src/runner.ts
  js/package.json
  js/types/.gitignore
  js/types/README.md
  js/types/package.json
  js/types/tsconfig.json
  js/yarn.lock
  lerna.json
  package.json
  yarn.lock
Labels: Status: Review Needed

#149 UI for proof test with cid
  README.md
  filecoindot-cli/README.md
  ui/.env.example
  ui/.eslintrc.json
  ui/.gitignore
  ui/.nvmrc
  ui/README.md
  ui/package.json
  ui/public/favicon.ico
  ui/public/index.html
  ui/public/manifest.json
  ui/public/robots.txt
  ui/src/App.css
  ui/src/App.test.tsx
  ui/src/App.tsx
  ui/src/components/layout/Center.tsx
  ui/src/constants/substrate.ts
  ui/src/containers/AccountSelect/index.tsx
  ui/src/containers/Header/index.tsx
  ui/src/containers/Settings/index.tsx
  ui/src/containers/UserSpace/index.tsx
  ui/src/contexts/AccountsContext.tsx
  ui/src/contexts/ApiContext.tsx
  ui/src/hooks/useDidUpdateEffect.tsx
  ui/src/index.css
  ui/src/index.tsx
  ui/src/logo.svg
  ui/src/pages/MintNFT.tsx
  ui/src/pages/NFTList.tsx
  ui/src/proof.ts
  ui/src/react-app-env.d.ts
  ui/src/reportWebVitals.ts
  ui/src/setupTests.ts
  ui/tsconfig.json
Labels: Status: Approved

#158 doc(rpc): update curl params for setting rpc endpoint
  README.md
Labels: Status: Review Needed

#160 chore(js): include source-map in js packages
  js/e2e/package.json
  js/types/package.json
  lerna.json
Labels: Status: Review Needed

#163 chore(docker): add docker chapter in readme
  .dockerignore
  Cargo.lock
  Dockerfile
  README.md
  filecoindot/src/ocw/tests/mod.rs
  js/e2e/src/runner.ts
Labels: Status: Review Needed

#181 feat(ocw): check relayer in ocw
  filecoindot/src/ocw/mod.rs
  filecoindot/src/ocw/result.rs
  filecoindot/src/tests/ocw.rs
Labels: Status: Review Needed
